project:
  name: chell
  entry_points: |
    [console_scripts]
    chell=chell.cli.main:chell_cli
personnel:
  author: Keenan W. Wilkinson
  author_email: keenanwilkinson@outlook.com
description:
  description: Custom multi-purpose developer tool
build:
  version: 0.0.0
  packages:
    - src
    - src/chell
  py_modules:
    - src.chell.cli.main
